import { CrawlerFiles } from "./_components/crawler-files";
import { OgImages } from "./_components/og-images";
import { PostList } from "./_components/post-list";
import { StreamingDemo } from "./_components/streaming-demo";
import { Section } from "./_components/ui/section";

// No metadata here: this page gets title.default and the description from
// layout.tsx, and the image from opengraph-image.tsx next to it.
export default function Page() {
  return (
    <main className="space-y-6">
      <header className="space-y-2">
        <h1 className="text-3xl font-semibold tracking-tight">
          Metadata and OG images
        </h1>
        <p className="text-zinc-600 dark:text-zinc-400">
          Next.js builds the head tags from the metadata object,
          generateMetadata and special files. The box at the bottom lists the
          tags of the current page.
        </p>
      </header>

      <Section
        title="1. Static metadata"
        description="layout.tsx exports a metadata object with a title template, a default title, a description, openGraph and twitter fields. This page defines nothing, so it shows the defaults."
      >
        <p className="text-sm">
          The root layout sets metadataBase, so relative image URLs become
          absolute ones.
        </p>
      </Section>

      <Section
        title="2. generateMetadata"
        description="Each post page reads its title and description from the fake database. React.cache makes the metadata and the page share one query."
      >
        <PostList />
      </Section>

      <Section
        title="3. Streaming metadata"
        description="On a dynamic page the UI is sent first and the metadata tags follow when generateMetadata resolves."
      >
        <StreamingDemo />
      </Section>

      <Section
        title="4. Generated OG images"
        description="opengraph-image.tsx files draw these PNGs with ImageResponse. The deeper file wins for its own route."
      >
        <OgImages />
      </Section>

      <Section
        title="5. robots.txt and sitemap.xml"
        description="Generated by src/app/robots.ts and src/app/sitemap.ts, for the whole site. They must live in the root of app."
      >
        <CrawlerFiles />
      </Section>
    </main>
  );
}
