import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "about olaghe aziz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/about">) {
  return (
    <>
      <h1 className=" flex  items-center justify-center  text-amber-400 text-lg font-semibold h-16 bg-amber-700 dark:text-zinc-50">
        salam olaghe aziz halet chetore
      </h1>

      {children}
    </>
  );
}
