import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="flex h-16 w-full items-center justify-center border-b border-zinc-200 bg-white px-8 dark:border-zinc-800 dark:bg-black">
          <h1 className="text-lg font-semibold text-zinc-950 dark:text-zinc-50">
            salam olaghe aziz halet chetore
          </h1>
        </header>
        {children}
      </body>
    </html>
  );
}
